RTRDoubleArmV7:
  tohoku_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - MFRAME
      - BLOCK
      - BOOM
      - ARM
      - TOHKU_PITCH
      - TOHKU_ROLL
    gains:
      MFRAME:
        p: 200000
        i: 20000
        d: 0
      BLOCK:
        p: 150000
        i: 15000
        d: 0
      BOOM:
        p: 150000
        i: 10000
        d: 0
      ARM:
        p: 100000
        i: 5000
        d: 0
      TOHKU_PITCH:
        p: 30000
        i: 500
        d: 0
      TOHKU_ROLL:
        p: 20000
        i: 500
        d: 0       
  mani_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - UFRAME
      - MNP_SWING
      - MANIBOOM
      - MANIARM
      - MANIELBOW
      - YAWJOINT
      - HANDBASE
    gains:
      UFRAME:
        p: 150000
        i: 15000
        d: 0
      MNP_SWING:
        p: 50000
        i: 1000
        d: 0
      MANIBOOM:
        p: 100000
        i: 3000
        d: 0
      MANIARM:
        p: 80000
        i: 2000
        d: 0
      MANIELBOW:
        p: 30000
        i: 500
        d: 0
      YAWJOINT:
        p: 20000
        i: 500
        d: 0
      HANDBASE:
        p: 500
        i: 20
        d: 0
  tohoku_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - TOHKU_TIP_01
      - TOHKU_TIP_02
    gains:
      TOHKU_TIP_01:
        p: 500
        i: 0
        d: 50
      TOHKU_TIP_02:
        p: 500
        i: 0
        d: 50
  mani_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - PUSHROD
    gains:
      PUSHROD:
        p: 50000
        i: 0
        d: 5000
