RTRDoubleArmV7:
  tohoku_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - MFRAME
      - BLOCK
      - BOOM
      - ARM
      - TOHKU_PITCH
      - TOHKU_ROLL
    gains:
      MFRAME:
        p: 200000
        i: 0
        d: 20000
      BLOCK:
        p: 150000
        i: 0
        d: 15000
      BOOM:
        p: 150000
        i: 0
        d: 10000
      ARM:
        p: 100000
        i: 0
        d: 5000
      TOHKU_PITCH:
        p: 30000
        i: 0
        d: 500
      TOHKU_ROLL:
        p: 20000
        i: 0
        d: 500       
  mani_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - UFRAME
      - MNP_SWING
      - MANIBOOM
      - MANIARM
      - MANIELBOW
      - YAWJOINT
      - HANDBASE
    gains:
      UFRAME:
        p: 150000
        i: 0
        d: 15000
      MNP_SWING:
        p: 50000
        i: 0
        d: 1000
      MANIBOOM:
        p: 100000
        i: 0
        d: 3000
      MANIARM:
        p: 80000
        i: 0
        d: 2000
      MANIELBOW:
        p: 30000
        i: 0
        d: 500
      YAWJOINT:
        p: 20000
        i: 0
        d: 500
      HANDBASE:
        p: 500
        i: 0
        d: 20
  tohoku_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - TOHKU_TIP_01
      - TOHKU_TIP_02
    gains:
      TOHKU_TIP_01:
        p: 500
        i: 0
        d: 50
      TOHKU_TIP_02:
        p: 500
        i: 0
        d: 50
  mani_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - PUSHROD
    gains:
      PUSHROD:
        p: 50000
        i: 0
        d: 5000
